name: Test Manual Input

on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Apply Terraform changes?"
        required: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print input
        run: |
          echo "Apply = ${{ inputs.apply }}"

      - name: Apply step
        if: ${{ inputs.apply }}
        run: |
          echo "Running Apply..."

      - name: Skip step
        if: ${{ !inputs.apply }}
        run: |
          echo "Apply was not selected."
